const STATIONS = [
  {
    name: "GreenTech Charger",
    address: "123 Elm St",
    price: 3,
    rating: 4.5,
    distance: 1.2,
    types: "QAE Combo CCS,Mesla Supercharger",
    id: "aaa",
    image: "https://storage.googleapis.com/greentech.jpg",
  },
  {
    name: "EcoCharge Station",
    address: "456 Oak Ave",
    price: 2,
    rating: 4,
    distance: 0.8,
    types: "SHAdeMO,Mesla Supercharger",
    id: "bbb",
    image: "https://storage.googleapis.com/ecocharge.jpg",
  },
  {
    name: "FastVolt Hub",
    address: "789 Pine Blvd",
    price: 5,
    rating: 4.8,
    distance: 1.5,
    types: "T1772 (T-plug),QAE Combo CCS",
    id: "ccc",
    image: "https://storage.googleapis.com/fastvolt.jpg",
  },
  {
    name: "ZapDrive Charger",
    address: "101 Maple Rd",
    price: 3.5,
    rating: 4.2,
    distance: 2.0,
    types: "SHAdeMO,QAE Combo CCS",
    id: "ddd",
    image: "https://storage.googleapis.com/zapdrive.jpg",
  },
  {
    name: "ChargePro Station",
    address: "202 Birch Ln",
    price: 4.5,
    rating: 5,
    distance: 1.0,
    types: "Mesla Supercharger,T1772 (T-plug)",
    id: "eee",
    image: "https://storage.googleapis.com/chargepro.jpg",
  },
];

export default STATIONS;
